/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.phone.ui;

import com.phone.dao.DonHangDAO;
import com.phone.entity.DonHangg;
import com.phone.utils.Auth;
import com.phone.utils.MsgBox;
import com.phone.utils.XImage;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author vinhp
 */
public class DonHang2 extends javax.swing.JDialog {

	DonHangDAO donhangdao = new DonHangDAO();
	int row = 0;

	/**
	 * Creates new form DonHang2
	 */
	public DonHang2(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
		init();
	}

	void init() {
		setIconImage(XImage.getAppIcon());
		setLocationRelativeTo(null);
		setTitle("Edusys - Đơn hàng");
		fillTable();
	}

	void fillTable() {
		DefaultTableModel model = (DefaultTableModel) tbldonhang.getModel();
		model.setRowCount(0);
		try {
			List<DonHangg> list = donhangdao.selectAll();
			for (DonHangg dh : list) {
				Object[] row = {
					dh.getMaDH(),
					dh.getMaKH(),
					dh.getNgayDH(),
					dh.getDiachiGH(),
					dh.getTrangThai()};
				model.addRow(row);
			}
		} catch (Exception e) {
			e.printStackTrace();
			MsgBox.alter(this, "Lỗi truy vấn dữ liệu");
		}
	}

	void setForm(DonHangg model) {
		txtMaHD.setText(String.valueOf(model.getMaDH()));
		txtMaKH.setText(model.getMaKH());
		txtNgayDat.setText(model.getNgayDH().toString());
		txtDiaChi.setText(model.getDiachiGH());
		txt_Trangthai.setText(model.getTrangThai());
	}

	DonHangg getForm() {
		SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");

		Date ngayDH = null;
		try {
			ngayDH = df.parse(txtNgayDat.getText());
		} catch (ParseException e) {
			// xử lý ngoại lệ parse date
		}

		DonHangg model = new DonHangg();
		model.setMaDH(Integer.parseInt(txtMaHD.getText()));
		model.setMaKH(txtMaKH.getText());
		model.setNgayDH(ngayDH);
		model.setDiachiGH(txtDiaChi.getText());
		model.setTrangThai(txt_Trangthai.getText());
		return model;
	}

	void edit() {
		try {
			Integer MaDH = (int) tbldonhang.getValueAt(this.row, 0);
			DonHangg dh = donhangdao.selectById(MaDH);
			this.setForm(dh);
			tabs.setSelectedIndex(0);

		} catch (Exception e) {
			MsgBox.alter(this, "Lỗi truy vấn dữ liệu Edit");
		}
	}

	boolean ValiateForm() {
		String maHD = txtMaHD.getText();

		if (!maHD.matches("^\\d+$")) {
			JOptionPane.showMessageDialog(this, "Mã hóa đơn chỉ được chứa số");
			return false;
		}

		String maKH = txtMaKH.getText();

		if (!maKH.matches("^[a-zA-Z0-9]+$")) {
			JOptionPane.showMessageDialog(this, "Mã KH chỉ được chứa chữ cái và số");
			return false;
		}

		SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");

		try {
			df.parse(txtNgayDat.getText());
		} catch (ParseException e) {
			JOptionPane.showMessageDialog(this, "Ngày đặt không đúng định dạng");
			return false;
		}
		
		
		String diaChi = txtDiaChi.getText();

		if (diaChi.trim().equals("")) {
			JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống");
			return false;
		}
		String pattern = "^[\\p{L}\\p{M}\\s]+$";

		if (!Pattern.matches(pattern, txt_Trangthai.getText())) {
			JOptionPane.showMessageDialog(this, "Trạng thái không hợp lệ!");
			return false;
		}
		return true;
	}

	void insert() {
		DonHangg model = getForm();
		try {
			donhangdao.insert(model);
			this.fillTable();
			this.clearForm();
			MsgBox.alter(this, "Đặt hàng thành công");
		} catch (Exception e) {

			MsgBox.alter(this, "Đặt hàng thất bại!");
		}
	}

	void update() {
		fillTable();
		DonHangg model = getForm();
		try {
			donhangdao.update(model);
			fillTable();
			MsgBox.alter(this, "Cập nhật thành công!");
		} catch (Exception e) {
			MsgBox.alter(this, "Cập nhật thất bại!");
		}
	}

	void delete() {
		if (!Auth.isManager()) {
			MsgBox.alter(this, "Bạn không có quyền xóa đơn hàng  !");
		} else {
			if (MsgBox.confirm(this, "Bạn thực sự muốn xóa đơn hàng này ?")) {
				String mahd = txtMaHD.getText();
				try {
					donhangdao.delete(mahd);
					this.fillTable();
					this.clearForm();
					MsgBox.alter(this, "Xóa thành công !");
				} catch (Exception e) {
					MsgBox.alter(this, "Xóa thất bại !");
				}
			}
		}

	}

	void clearForm() {
		txtMaHD.setText("");
		txtMaKH.setText("");
		txtNgayDat.setText("");
		txtDiaChi.setText("");
		txt_Trangthai.setText("");
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jScrollPane2 = new javax.swing.JScrollPane();
                jTable1 = new javax.swing.JTable();
                jTabbedPane1 = new javax.swing.JTabbedPane();
                jLabel1 = new javax.swing.JLabel();
                tabs = new javax.swing.JTabbedPane();
                jPanel2 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                txtMaHD = new javax.swing.JTextField();
                jLabel3 = new javax.swing.JLabel();
                txtMaKH = new javax.swing.JTextField();
                txtNgayDat = new javax.swing.JTextField();
                txtDiaChi = new javax.swing.JTextField();
                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                btnThem = new javax.swing.JButton();
                btnSua = new javax.swing.JButton();
                btnXoa = new javax.swing.JButton();
                btnMoi = new javax.swing.JButton();
                jLabel6 = new javax.swing.JLabel();
                txt_Trangthai = new javax.swing.JTextField();
                jPanel1 = new javax.swing.JPanel();
                jScrollPane1 = new javax.swing.JScrollPane();
                tbldonhang = new javax.swing.JTable();

                jTable1.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                jScrollPane2.setViewportView(jTable1);

                setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
                jLabel1.setForeground(new java.awt.Color(0, 0, 255));
                jLabel1.setText("Cập nhật trạng thái đơn hàng");

                jLabel2.setText("Mã đơn hàng");

                jLabel3.setText("Mã khách hàng");

                jLabel4.setText("Địa chỉ");

                jLabel5.setText("Ngày đặt");

                btnThem.setText("Đặt hàng");
                btnThem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnThemActionPerformed(evt);
                        }
                });

                btnSua.setText("Sửa");
                btnSua.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnSuaActionPerformed(evt);
                        }
                });

                btnXoa.setText("Xóa");
                btnXoa.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnXoaActionPerformed(evt);
                        }
                });

                btnMoi.setText("Mới");
                btnMoi.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnMoiActionPerformed(evt);
                        }
                });

                jLabel6.setText("Trạng thái");

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txtMaHD)
                                                        .addComponent(txtNgayDat, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))
                                                .addGap(33, 33, 33)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel6))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(txt_Trangthai)
                                                        .addComponent(txtMaKH, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(55, Short.MAX_VALUE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnThem)
                                .addGap(18, 18, 18)
                                .addComponent(btnSua)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoa)
                                .addGap(18, 18, 18)
                                .addComponent(btnMoi)
                                .addGap(122, 122, 122))
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(txtMaKH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtNgayDat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(txt_Trangthai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addGap(45, 45, 45)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnThem)
                                        .addComponent(btnSua)
                                        .addComponent(btnXoa)
                                        .addComponent(btnMoi))
                                .addGap(33, 33, 33))
                );

                tabs.addTab("Cập Nhật", jPanel2);

                tbldonhang.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null},
                                {null, null, null, null, null}
                        },
                        new String [] {
                                "MaHD", "MAKH", "NGÀY ĐẶT", "ĐỊA CHỈ GIAO HÀNG", "Trạng thái"
                        }
                ) {
                        boolean[] canEdit = new boolean [] {
                                false, false, false, false, false
                        };

                        public boolean isCellEditable(int rowIndex, int columnIndex) {
                                return canEdit [columnIndex];
                        }
                });
                tbldonhang.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mousePressed(java.awt.event.MouseEvent evt) {
                                tbldonhangMousePressed(evt);
                        }
                });
                jScrollPane1.setViewportView(tbldonhang);

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 574, Short.MAX_VALUE)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE))
                );

                tabs.addTab("Đơn Hàng", jPanel1);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(tabs)
                                .addContainerGap())
                        .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
	 if(ValiateForm()){
	update();
	 }
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
	    // TODO add your handling code here:
	    clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
	    // TODO add your handling code here:
	    delete();
    }//GEN-LAST:event_btnXoaActionPerformed

        private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
		if (ValiateForm()) {
			insert();
		}
        }//GEN-LAST:event_btnThemActionPerformed

        private void tbldonhangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbldonhangMousePressed
              if (evt.getClickCount() == 2) {
            this.row = tbldonhang.rowAtPoint(evt.getPoint());
            edit();
        }
        }//GEN-LAST:event_tbldonhangMousePressed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(DonHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(DonHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(DonHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(DonHang2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				DonHang2 dialog = new DonHang2(new javax.swing.JFrame(), true);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnMoi;
        private javax.swing.JButton btnSua;
        private javax.swing.JButton btnThem;
        private javax.swing.JButton btnXoa;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JLabel jLabel6;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JScrollPane jScrollPane2;
        private javax.swing.JTabbedPane jTabbedPane1;
        private javax.swing.JTable jTable1;
        private javax.swing.JTabbedPane tabs;
        private javax.swing.JTable tbldonhang;
        private javax.swing.JTextField txtDiaChi;
        private javax.swing.JTextField txtMaHD;
        private javax.swing.JTextField txtMaKH;
        private javax.swing.JTextField txtNgayDat;
        private javax.swing.JTextField txt_Trangthai;
        // End of variables declaration//GEN-END:variables
}
